### ISSUE TITLE
needs hardening

### ISSUE THREAD

**Issue by parmentelat** [fit-r2lab/r2lab-sidecar#1]
r2lab.inria.fr has migrated to fedora27 and in the process, new kinds of failures seem to have happened

particularly the one below which I believe I saw several times already

failure has been mitigated with a systemd auto-restart instruction in the service file, but this may still be worth a glance

```
Jan 31 11:01:01 r2lab.pl.sophia.inria.fr bash[19401]: Wed Jan 31 2018 11:01:01 GMT+0100 (CET) sidecar  strack trace is TypeError: news_infos.forEach is not a function
Jan 31 11:01:01 r2lab.pl.sophia.inria.fr bash[19401]:     at merge_news_into_complete (/root/r2lab-sidecar/sidecar.js:286:16)
Jan 31 11:01:01 r2lab.pl.sophia.inria.fr bash[19401]:     at update_dbfile_from_news (/root/r2lab-sidecar/sidecar.js:269:20)
Jan 31 11:01:01 r2lab.pl.sophia.inria.fr bash[19401]:     at Socket.<anonymous> (/root/r2lab-sidecar/sidecar.js:135:22)
Jan 31 11:01:01 r2lab.pl.sophia.inria.fr bash[19401]:     at emitTwo (events.js:126:13)
Jan 31 11:01:01 r2lab.pl.sophia.inria.fr bash[19401]:     at Socket.emit (events.js:214:7)
Jan 31 11:01:01 r2lab.pl.sophia.inria.fr bash[19401]:     at /root/r2lab-sidecar/node_modules/socket.io/lib/socket.js:503:12
Jan 31 11:01:01 r2lab.pl.sophia.inria.fr bash[19401]:     at _combinedTickCallback (internal/process/next_tick.js:131:7)
Jan 31 11:01:01 r2lab.pl.sophia.inria.fr bash[19401]:     at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by parmentelat** [comment]
this was about the js version
